task commit
InvoiceBox/backend-test-app pull request #1
Opened 2021-05-22 15:09 UTC by gadmag

Task PR

2021-05-24 14:15 UTC, nofirg requested changes

2021-05-24 14:15 UTC, nofirg commented on src/Presentation/Controller/OrderController.php
> +    public function removeItemOrder(Request $request, array $readSerializationGroups, OrderItemRepository $orderItemRepository): JsonResponse
есть сущность OrderItem, логично было бы ее удалять по прямому идентификатору, а не перебирать все позиции в поисках нужной по идентификатору продукта

2021-05-25 06:27 UTC, mikhailovv commented on src/Presentation/Controller/OrderController.php
> +        return $this->serializer->createJsonResponse($order, $readSerializationGroups);
> Не могу найти место, где пересчитывается сумма заказа.
> Так же не помешала бы транзакция

Сумма заказа пересчитывается вот этим вызовом)

\BackendTestApp\Domain\Entity\Order
/**
 * @ORM\PreUpdate
 */
public function setSumQtyValue()

2021-05-25 08:23 UTC, gadmag commented on src/Presentation/Controller/ProductController.php
> +        );
по примеру модели Example, используется DeserializationContext

2021-05-25 08:24 UTC, gadmag commented on src/Domain/Entity/Order.php
> +    public function deleteAllItems(): self
Добавил возможность удалять разом все items заказа

2021-05-25 08:25 UTC, gadmag commented on src/Presentation/Controller/OrderController.php
> +    public function removeItemOrder(Request $request, array $readSerializationGroups, OrderItemRepository $orderItemRepository): JsonResponse
Добавил такую возможность

2021-07-14 13:56 UTC, closed without merging